# MapR Volume Driver Plugin for Kubernetes

# Using the MapR Volume Driver Plugin for dynamic provisioning

# Provisioning: dynamic
# Container:    busybox

# MapR Apps Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: mapr-apps
  labels:
    name: mapr-apps

# MapR Apps ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mapr-apps-sa
  namespace: mapr-apps


# Secret to authenticate with MapR Converged Data Platform
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-provisioner-secrets
  namespace: mapr-apps
type: Opaque
data:
# base64 encoding: "echo -n '<username/password>' | base64" eg:
# echo -n 'mapr' | base64
  MAPR_CLUSTER_USER: "bWFwcg=="
  MAPR_CLUSTER_PASSWORD: "bWFwcg=="

# Ticket to authenticate with MapR Converged Data Platform
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-ticket-secret
  namespace: mapr-apps
type: Opaque
data:
# To create a Ticket:
# 1. maprlogin password -user mapr
# 2. echo -n $(cat /tmp/maprticket_####) | base64
# 3. combine 6 lines base64 output in single CONTAINER_TICKET line:
  # user: mapr
  CONTAINER_TICKET: ZGVtby5tYXByLmNvbSBxSkxrVEhoeGtFRlUxU2p3a29NcUN4ZVhra1hPS2JwTVphNllTQ3FpaENnYlRhVkQyOEUrTTJhSng4dWljdlp1aHozR1pOS2pCNW8wRmFjRlVWRGVvVEZYVzhXdElTUG5DOEp2Q01zZG1PcEFIZ2V6eWdrekU5V1ZwaGVoT2RMcWFyaVdGVmtZSjEwVngzNG85RFFzM0U5YmdFWFZ0bVJNQ2JiREd6THpJbzVvVDBpTkU5OUlhT2dySnN3RE9SYmd6bFRBRjBzVVlHK05iL09mUkVWNUV1SFpKZk13M3NxMUY3MjI1bjJHN3hBZkhCQXFGb0dDSGhoNnhvVm45MmNEZHZJTGk4anVkU1ZMSzd0SFpFZzRZUFJXazdZUU0rdz0=

# StorageClass for MapR Converged Data Platform
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: maprfs-sc-busybox-secure-dynamic
   namespace: mapr-apps
provisioner: mapr.com/maprfs
parameters:
    # Configure below MapR cluster details to reflect your MapR cluster configuration
    restServers: "172.18.14.32:8443"
    cldbHosts: "172.18.14.32"
    cluster: "demo.mapr.com"
    securityType: "secure"
    ticketSecretName: "mapr-ticket-secret"
    ticketSecretNamespace: "mapr-apps"
    maprSecretName: "mapr-provisioner-secrets"
    maprSecretNamespace: "mapr-apps"
    namePrefix: "busybox"
    mountPrefix: "/busybox"
    reclaimPolicy: "Retain"
    advisoryquota: "100M"
    type: "rw"
    mount: "1"


# PersistentVolumeClaim for MapR Converged Data Platform
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maprfs-pvc-busybox-secure-dynamic
  namespace: mapr-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: maprfs-sc-busybox-secure-dynamic
  resources:
    requests:
      storage: 300M
